# Generated by Django 3.0 on 2019-12-07 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_Curso', models.CharField(max_length=100)),
                ('data_Inicio', models.DateField()),
                ('num_Alunos', models.IntegerField()),
                ('num_Prof', models.IntegerField()),
                ('alunos_Formados', models.IntegerField()),
                ('descricao', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeEvento', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('descricao', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Evento',
            },
        ),
        migrations.CreateModel(
            name='Professores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_Prof', models.CharField(max_length=100)),
                ('formacao', models.CharField(default='Eng. Computação', max_length=100)),
                ('titulo_Academico', models.CharField(max_length=30)),
                ('ano_Inicio', models.CharField(max_length=4)),
                ('turmas', models.IntegerField()),
                ('membro_Organizacao', models.BooleanField(default=True)),
                ('curso_Leciona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_neilytaTec1.Cursos')),
            ],
            options={
                'verbose_name_plural': 'Professores',
            },
        ),
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_aluno', models.CharField(max_length=100)),
                ('ano', models.IntegerField(default=3)),
                ('genero', models.CharField(default='M', max_length=1)),
                ('idade', models.IntegerField()),
                ('eh_destaque', models.BooleanField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_neilytaTec1.Cursos')),
            ],
            options={
                'verbose_name_plural': 'Alunos',
            },
        ),
    ]
