# Generated by Django 3.0 on 2019-12-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_neilytaTec1', '0002_auto_20191207_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='genero',
            field=models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMININO', 'Feminino')], max_length=30),
        ),
    ]
