# Generated by Django 3.0 on 2019-12-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_neilytaTec1', '0003_auto_20191207_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='nome_Curso',
            field=models.CharField(choices=[('TÉCNICO EM INFORMÁTICA', 'TÉCNICO EM INFORMÁTICA'), ('TÉCNICO EM AGROPECUÁRIA', 'TÉCNICO EM EM AGROPECUÁRIA'), ('TÉCNICO EM ELETROMECÂNICA', 'TÉCNICO EM ELETROMECÂNICA'), ('TÉCNICO EM FINANÇAS', 'TÉCNICO EM FINANÇAS')], max_length=30),
        ),
        migrations.AlterField(
            model_name='professores',
            name='titulo_Academico',
            field=models.CharField(choices=[('BACHAREL', 'Bacharel'), ('ESPECIALISATA', 'Especialista'), ('MESTRE', 'Mestre'), ('PHD', 'PhD')], max_length=30),
        ),
    ]
