# Generated by Django 2.2.1 on 2019-05-28 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ano', models.DateField()),
                ('curso', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=1)),
                ('idade', models.IntegerField(max_length=3)),
                ('ehdestaque', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('anoInicio', models.DateField()),
                ('numAlunos', models.IntegerField()),
                ('numProf', models.IntegerField()),
                ('alunosFormados', models.IntegerField()),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('image', models.ImageField(height_field='picture_height', max_length=255, upload_to='', width_field='picture_width')),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cursoLeciona', models.CharField(max_length=100)),
                ('anoInicio', models.DateField()),
                ('numTurmas', models.IntegerField()),
                ('tituloAc', models.CharField(max_length=30)),
            ],
        ),
    ]
