# Generated by Django 2.2.1 on 2019-05-28 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursodjango', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ano', models.DateField()),
                ('genero', models.CharField(max_length=1)),
                ('idade', models.IntegerField()),
                ('ehdestaque', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Professores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tituloAc', models.CharField(max_length=30)),
                ('anoInicio', models.DateField()),
                ('numTurmas', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Aluno',
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
        migrations.AlterField(
            model_name='evento',
            name='image',
            field=models.ImageField(max_length=255, upload_to=''),
        ),
        migrations.RenameModel(
            old_name='Curso',
            new_name='Cursos',
        ),
        migrations.AddField(
            model_name='professores',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursodjango.Cursos'),
        ),
        migrations.AddField(
            model_name='alunos',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursodjango.Cursos'),
        ),
    ]
