# Generated by Django 2.2.1 on 2019-05-28 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursodjango', '0002_auto_20190528_1248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alunos',
            options={'verbose_name_plural': 'Alunos'},
        ),
        migrations.AlterModelOptions(
            name='cursos',
            options={'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='professores',
            options={'verbose_name_plural': 'Professores'},
        ),
    ]
