# Generated by Django 2.2.1 on 2019-05-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursodjango', '0003_auto_20190528_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='ano',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='alunos',
            name='genero',
            field=models.CharField(default='M', max_length=1),
        ),
    ]
