# Generated by Django 2.2.1 on 2019-05-29 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursodjango', '0004_auto_20190528_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursos',
            old_name='anoInicio',
            new_name='dataInicio',
        ),
    ]
