# Generated by Django 2.2.1 on 2019-05-30 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursodjango', '0007_auto_20190529_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='image',
            field=models.ImageField(upload_to='images2'),
        ),
    ]
