# Generated by Django 2.2.1 on 2019-05-31 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursodjango', '0011_auto_20190530_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professores',
            old_name='numTurmas',
            new_name='turmas',
        ),
        migrations.AddField(
            model_name='professores',
            name='membroOrg',
            field=models.BooleanField(default=True),
        ),
    ]
