# Generated by Django 2.2.1 on 2019-06-02 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursodjango', '0012_auto_20190531_0242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alunos',
            old_name='nome',
            new_name='nomeAlu',
        ),
        migrations.RenameField(
            model_name='cursos',
            old_name='nome',
            new_name='nomeCurso',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='nome',
            new_name='nomeEvento',
        ),
        migrations.RenameField(
            model_name='professores',
            old_name='nome',
            new_name='nomeProf',
        ),
    ]
