# Generated by Django 3.0 on 2019-12-07 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursodjango', '0013_auto_20190602_0105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alunos',
            old_name='ehdestaque',
            new_name='eh_destaque',
        ),
        migrations.RenameField(
            model_name='alunos',
            old_name='nomeAlu',
            new_name='nome_aluno',
        ),
        migrations.RenameField(
            model_name='cursos',
            old_name='alunosFormados',
            new_name='alunos_Formados',
        ),
        migrations.RenameField(
            model_name='cursos',
            old_name='dataInicio',
            new_name='data_Inicio',
        ),
        migrations.RenameField(
            model_name='cursos',
            old_name='nomeCurso',
            new_name='nome_Curso',
        ),
        migrations.RenameField(
            model_name='cursos',
            old_name='numAlunos',
            new_name='num_Alunos',
        ),
        migrations.RenameField(
            model_name='cursos',
            old_name='numProf',
            new_name='num_Prof',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='nomeEvento',
            new_name='nome_Evento',
        ),
        migrations.RenameField(
            model_name='professores',
            old_name='anoInicio',
            new_name='ano_Inicio',
        ),
        migrations.RenameField(
            model_name='professores',
            old_name='cursoLec',
            new_name='curso_Leciona',
        ),
        migrations.RenameField(
            model_name='professores',
            old_name='membroOrg',
            new_name='membro_Organizacao',
        ),
        migrations.RenameField(
            model_name='professores',
            old_name='nomeProf',
            new_name='nome_Prof',
        ),
        migrations.RenameField(
            model_name='professores',
            old_name='tituloAc',
            new_name='titulo_Academico',
        ),
    ]
